package org.awdevelopment.smithlab.config;

public enum ConfigOption {
    INPUT_FILE,
    MODE,
    OUTPUT_FILE,
    OUTPUT_TYPE,
    WRITE_TO_DIFFERENT_FILE,
    SORT_OPTION,
    NUMBER_OF_REPLICATES,
    EMPTY_INPUT_SHEET_NAME,
    CONDITION_STRAIN_OUTPUT,
    GUI,
    CONDITIONS,
    STRAINS,
    DAYS,
    NUM_DAYS,
    INCLUDE_BASELINE_COLUMN,
    SAMPLE_LABELING_TYPE,
    NUM_CONDITIONS,
    NUM_STRAINS,
    USING_NUM_DAYS,
    USING_NUM_CONDITIONS,
    USING_NUM_STRAINS
}
